### ISSUE TITLE
Having issues with sort

### ISSUE THREAD

**Issue by signorekai** [carrot/roots-contentful#40]
I'm having some issues trying to sort content type with a date field (only Date), wondering if I can get some help.

**app.coffee:**
```
extensions: [
    contentful
      access_token: ''
      space_id: ''
      content_types:
        posts:
          id: ''
          filters: { }
          sort: (a,b) ->
            parseInt( moment(b.date, 'YYYY-MM-DD').unix() ) - parseInt( moment(a.date, 'YYYY-MM-DD').unix() )
```

The Date field should return something along the lines of 2015-11-05

I already have moment required; it's working elsewhere in the views, just not working here. The 'posts' content type just end up following some sort of random order. Would appreciate some help here!
