### ISSUE TITLE
Transform function not working

### ISSUE THREAD

**Issue by FranzSkuffka** [carrot/roots-contentful#44]
I have the following transform function:
```
formatEvent = (event) ->
    event.date = 'hello'
    console.log event
    delete event.sys
    event
```

My contentful config looks like this:
```
    contentful
        access_token: 'XXXXX'
        space_id: 'zz4gw0sowa4j'
        content_types:
            member:
                id: '2JULZsVvqE88AASqOqwCsg'
            event:
                id: '4U01XhjOU0qiaiWUS0k4wk'
                transform: formatEvent
            document:
                id: '6p4N5fxOWkCWs4SOIKCOum'
            eventLocation:
                id: '7HRiLDEM8wMiMGyOyCewcm'
```

My function is not being executed, I can tell because nothing is logged to the console. The only difference I can make out between this and the unit tests is that here I use an object instead of an array. 
My views do have access to the content. Everything is working fine except the transform.

Any ideas?
